version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  build:
    commands:
      - sam build

  post_build:
    commands:
      - sam deploy --guided

artifacts:
  type: zip
  files:
    - template.yml