version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - python -m unittest discover tests

  build:
    commands:
      - sam build

  post_build:
    commands:
      - sam package --output-template-file template.yml --s3-bucket kvsravindrareddy2020

artifacts:
  type: zip
  files:
    - template.yml