version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  build:
    commands:
      - sam build

  post_build:
    commands:
      - sam package --template-file template.yml --output-template-file template-out.yml --s3-bucket kvsravindrareddy2020

artifacts:
  type: zip
  files:
    - template-out.yml