version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - pip3 install --upgrade pip
      - pip3 install pipenv --user
      - pip3 install awscli aws-sam-cli
      #- sam build
      #- sam deploy -- guided
      - sam package --template-file template.yml --s3-bucket "codepipeline-ap-south-1-754048210511" --output-template-file packaged-template.yml
      #- sam deploy --template-file template.yaml --stack-name document-store  --s3-bucket sp-document-coder --capabilities CAPABILITY_IAM --region us-west-2 --output-template-file packaged-template.yml
#artifacts:
 # files:
  #  - packaged-template.yml