version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "document-store"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ri2v5z1dhfci"
s3_prefix = "document-store"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

